
samples: samples.tsv        # Complete the tab sep value file with the path to the files and their conditions

### Definition of the path Snakemake has to create
working_dir: "temp/"
result_dir:  "results/"

### Genome and annotations
refs:
  genome:
    "refs/S_lycopersicum_chromosomes.3.00.fa"
  proteins:
    "refs/ITAG3.2_proteins.fasta"
  gene_models:
    "refs/ITAG3.2_gene_models.gff"

### Software parameters
trimmomatic:
  adapters: "adapters.fasta"
  seedMisMatches: '2'
  palindromeClipTreshold: '30'
  simpleClipThreshold: '10'
  LeadMinTrimQual: '3'
  TrailMinTrimQual: '3'
  windowSize: '4'
  avgMinQual: '15'
  minReadLength: '40'
  phred: "-phred33" # phred: for illumina >1.8 the quality score are encoded by phred33

blast:
  evalue     : "1e-10"
  outFmt     : "6 qseqid evalue length mismatch salltitles"   # 6 for tab separated file.
  maxTargets : "1"

deseq2:
  maxfraction : '0.7'
